# Generated by Django 5.2.8 on 2026-04-28 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_restaurantsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('qty', 'Quantity')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='management.fooditem')),
            ],
        ),
    ]
