# Generated by Django 5.2.8 on 2026-05-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_foodvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsetting',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
