# Generated by Django 5.2.8 on 2026-05-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_restaurantsetting_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsetting',
            name='gstin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurantsetting',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
