# Generated by Django 5.2.8 on 2026-04-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0014_discountsetting_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='advance_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('advance_paid', 'Advance Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
