# Generated by Django 5.2.8 on 2026-04-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0016_order_tax_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountsetting',
            name='name',
        ),
        migrations.AddField(
            model_name='discountsetting',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='discountsetting',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Fixed Amount')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='discountsetting',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
