# Generated by Django 5.2.8 on 2026-04-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0017_remove_discountsetting_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountsetting',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='discountsetting',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='discountsetting',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='discountsetting',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20),
        ),
    ]
