# Generated by Django 5.2.8 on 2026-05-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0018_remove_discountsetting_discount_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
