# Generated by Django 5.2.8 on 2026-05-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0019_taxsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='daily_order_number',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
