# Generated by Django 5.2.8 on 2026-05-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0022_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='cashier_cus_phone_d13102_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='cashier_ord_created_692629_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='cashier_ord_status_f0f933_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_advance'], name='cashier_ord_is_adva_42c666_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_bulk'], name='cashier_ord_is_bulk_2e44ea_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['scheduled_time'], name='cashier_ord_schedul_179d13_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['paid_at'], name='cashier_ord_paid_at_bd705b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer'], name='cashier_ord_custome_d5e877_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='cashier_ord_order_i_8aa4da_idx'),
        ),
    ]
