# Generated by Django 5.2.8 on 2026-05-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0023_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='cashier_cus_phone_d13102_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='cashier_ord_created_692629_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='cashier_ord_status_f0f933_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='cashier_ord_is_adva_42c666_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='cashier_ord_is_bulk_2e44ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='cashier_ord_schedul_179d13_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='cashier_ord_paid_at_bd705b_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='cashier_ord_custome_d5e877_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='cashier_ord_order_i_8aa4da_idx',
        ),
    ]
