# Generated by Django 5.2.8 on 2026-05-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0024_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxsetting',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
