# Generated by Django 5.2.8 on 2026-05-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0025_alter_taxsetting_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
