# Generated by Django 5.2.8 on 2026-05-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0026_orderitem_variant_info'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='cashier_ord_created_eeba99_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='cashier_ord_status_f0f933_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_mode'], name='cashier_ord_payment_315c67_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_bulk'], name='cashier_ord_is_bulk_2e44ea_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_advance'], name='cashier_ord_is_adva_42c666_idx'),
        ),
    ]
