# Generated by Django 5.2.8 on 2026-05-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0027_order_cashier_ord_created_eeba99_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
