# Generated by Django 5.2.8 on 2026-05-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0028_order_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='available_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
