# Generated by Django 5.2.8 on 2026-05-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0029_customer_available_credit_customer_credit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credit_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_credit_order',
            field=models.BooleanField(default=False),
        ),
    ]
